

services:
  tomcat:
    build: ./tomcat
    image: tomcat:9.0.88-jre8
    container_name: tomcat9
    ports:
      - 8082:8080
    restart: on-failure
    depends_on:
      - postgresql
    networks:
      - eb

  postgresql:
    build: ./postgres
    image: postgres
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DBNAME: "kumulus"
      ALLOW_IP_RANGE: "0.0.0.0/0"
    restart: always
    networks:
      - eb

volumes:
  pg_data:

networks:
  eb: